language: php
php:
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - rm composer.lock
  - travis_retry composer -n update --prefer-dist

script:
  - composer lint
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls -v
